### ISSUE TITLE
Weather insights node is not working in United Kingdom region

### ISSUE THREAD

**Issue by binnes** [ibmets/node-red-bluemix-nodes#61]
The Weather insights node is not working in United Kingdom region. When using a bound service the following error is given : "**Weather Insights service call failed due to non-200 HTTP response to API call.**"   
When not using a bound service there is no configuration field available to add the host (https://twcservice.eu-gb.mybluemix.net) and looking at the node code it is hard coded to US region instance (https://twcservice.mybluemix.net), so all credentials for services deployed in United Kindom region will fail with "**Weather Insights service call failure due to authentication failure.**"

**Comment by jthomas** [comment]
Thanks for reporting this @binnes. I'll have a look over the next few days.

**Comment by binnes** [comment]
Any outlook on a fix for this issue?

**Comment by jthomas** [comment]
Apologies - this got lost in my backlog.

Looking over the existing code, if a service is bound to the application, it will pick up the host name automatically. It is only hardcoded when manually entering credentials. I've submitted a PR to add a manual host field to the editor configuration.

**Comment by knolleary** [comment]
Have published v1.1.10 with this fix.

**Comment by johnwalicki** [comment]
I'm getting this Weather Insights error in all of my CF applications that are bound to Weather-Insights in US South region.  The error started on Tuesday 6/6.  I've restarted the CF applications.  This particular Weather Company Data v2-Free service instance was provisioned in November 2016 and is bound to 6 CF applications.  All are failing with "Weather Insights service call failed due to non-200 HTTP response to API call."

**Comment by johnwalicki** [comment]
Bah - I've hit the 10000 call limit.
	
The Weather Company Data Free plan allows you to make a maximum of 10 calls to The Weather Company per minute, up to a maximum of 10,000 API calls, for each Bluemix Account. You can test the data in your applications without restrictions to geography, forecast type, or time series observations, with only a restriction on number of calls. When the maximum call limit is reached, the Free Plan will not allow any Weather Company data to be retrieved until the Cloud Service is upgraded to the Base, Standard, or Premium plan. You can have only one instance of the Weather Company Data service in the Free plan.

**Comment by fmlin429** [comment]
I got the same error today in US South Region.

**Comment by developersteve** [comment]
Did this get resolved? seem to be getting the same error as well
