### ISSUE TITLE
Can you please add node red to IBM BPM connector?

### ISSUE THREAD

**Issue by brettforbes** [ibmets/node-red-bluemix-nodes#62]
Hi,
Thanks for producing many excellent IBM nodes, yet I would definitely like to fire off business processes based on node red flows. Can you make a node red wrapper for the IBM BPM service?

**Comment by dceejay** [comment]
please use the mailing list or slack channels for suggestions and discussions. 

We don't know anything about the BPM service other than it's existence so will need to leave that to others who are closer to the topic than ourselves.

Does this help ? https://developer.ibm.com/bpm/videos/node-red-and-bpm/
